---
title: Joint clustering on expression and methylation
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(RColorBrewer)
library(gridExtra)
library(gplots)
library(corrplot)
library(ggdendro)
library(weights)
library(stringr)
library(weights)
source('viz.R')
```

```{r}
opts <- list()
opts$data_file <- '../data/join/data.rds'
opts$r_file <- '../gene/r.rds'
opts$genes_file <- '../data/expr/data_raw/subpopulation_lif_genes9.csv'
opts$init <- T
opts$name <- 'gene_body'
opts$n <- 300
```

```{r read, eval=opts$init}
read_genes <- function(f) {
  d <- read.csv(f, sep=',', head=T) %>% tbl_df
  names(d) <- c('ens_id', 'gene_id')
  return (d)
}

format_sample <- function(s) {
  l <- str_split(s, '_')
  l <- sapply(l, function(x) x[length(x)])
  return (l)
}

dat <- list()
dat$em <- readRDS(opts$data_file) %>%
  filter(name == opts$name) %>%
  mutate(sample=factor(sample, labels=format_sample(levels(sample)))) %>%
  droplevels
dat$r <- readRDS(opts$r_file) %>%
  filter(name == opts$name) %>% droplevels
dat$genes <- read_genes(opts$genes_file)
```


```{r prepro, eval=opts$init}
dat$s <- dat$em %>% group_by(name, id_.x, id_.y) %>%
  summarise(
    expr_mean = mean(expr),
    expr_var = var(expr),
    met_mean = weighted.mean(met, weight, na.rm=T),
    met_var = wtd.var(met, weight, na.rm=T)
    ) %>% ungroup
dat$s <- dat$s %>% inner_join(dat$r, by=c('name', 'id_.x', 'id_.y'))
```

```{r}
data_select <- function(n, by='met_var') {
  h <- dat$s %>% group_by(name, id_.x) %>% top_n(1, met_var) %>% ungroup
  h <- h %>% group_by(name) %>% top_n(n, met_var) %>% ungroup
  h <- h %>% select(name, id_.x, id_.y, met_var)
  return (h)
}

data_clust <- function(s) {
  em <- dat$em %>% semi_join(s, by=c('name', 'id_.x', 'id_.y')) %>%
    select(id_.x, id_.y, gene_id, sample, expr, met)
  e <- em %>% select(id_.y, gene_id, sample, expr) %>% spread(sample, expr)
  m <- em %>% select(id_.y, gene_id, sample, met) %>% spread(sample, met)
  rs <- dat$s %>% semi_join(s, by=c('name', 'id_.x', 'id_.y'))
  return (list(r=rs, e=e, m=m, em=em))
}

plot_tracks <- function(d) {
  tr <- plot_track(filter(d, param=='r')) +
    scale_fill_gradient2(low='royalblue', mid='white', 'high'='red2', name='r')
  te <- plot_track(filter(d, param=='expr_var')) +
    scale_fill_gradient(low='white', 'high'='red', name='var(expr)')
  tm <- plot_track(filter(d, param=='met_var')) +
    scale_fill_gradient(low='white', 'high'='royalblue2', name='var(met)')
  grid.arrange(te, tr, tm, ncol=3)
}

opts$clust <- list()
opts$clust$c1 <- c("F02", "E02", "C05", "B10", "B05", "D05", "E01", "H03", "E09", "C07", "B07", "F07", "C02")
opts$clust$c2 <- c("E07", "D04", "D09", "G01", "D07", "C10", "H01", "D01", "H02", "E05", "G07", "F03", "C03", "A07", "G05", "C01", "B01", "G09", "B04", "G06", "C04", "C09")
opts$clust_colors <- c('default'='forestgreen', 'c1'='navyblue', 'c2'='brown1')

samples_colors <- function(x) {
  h <- rep(opts$clust_colors['default'], length(x))
  for (n in names(opts$clust)) {
    h[x %in% opts$clust[[n]]] <- opts$clust_colors[n]
  }
  names(h) <- x
  return (h)
}

plot_heat <- function(d, xlab='value', col=NULL, col_colors=NULL,
  labRow=NA, ...) {
  d <- as.matrix(d)
  if (is.null(col)) {
    col <- rev(brewer.pal(9, 'Spectral'))
    col <- colorRampPalette(col)(50)
  }

  if (nrow(d) > 500) {
    dendro='column'
  } else {
    dendro = 'both'
  }

  col_colors <- samples_colors(colnames(d))

  p <- heatmap.2(d, density.info='none', trace='none', col=col,
    keysize=1.0, dendro=dendro, labRow=labRow,
    ColSideColors=col_colors,
    lwid=c(2, 5), key.title='', srtCol=45, key.xlab=xlab, ...)
  return (p)
}

plot_heat_expr <- function(dclust, col=NULL, ...) {
  d <- dclust$e %>% select(-id_.y) %>% to_matrix(rowcol='gene_id')
  if (is.null(col)) {
    col <- brewer_cols('OrRd')
  }
  pe <- plot_heat(d, col=col, xlab='Expression', ...)
  return (pe)
}

plot_heat_met <- function(dclust, col=NULL, ...) {
  d <- dclust$m %>% select(-id_.y) %>% to_matrix(rowcol='gene_id')
  if (is.null(col)) {
    col <- brewer_cols('PuBuGn', rev=F)
  }
  pm <- plot_heat(d, col=col, xlab='Methylation', ...)
  return (pm)
}
```

```{r}
dclust <- data_clust(data_select(opts$n))
```

```{r fig.width=10, fig.height=10}
pm <- plot_heat_met(dclust)
```

```{r fig.width=10, fig.height=10}
pe <- plot_heat_expr(dclust, Rowv=pm$rowDendrogram)
```

```{r fig.height=10, fig.width=2}
plot_tracks(data_track(dclust, pm))
```


```{r}
opts_chunk$set(eval=F)
```


## Gene-body: ordered by expression clustering

```{r}
dclust <- data_clust('gene_body', opts$n)
```

```{r fig.width=10, fig.height=10}
pe <- plot_heat_expr(dclust)
```

```{r fig.width=10, fig.height=10}
pm <- plot_heat_met(dclust, pe)
```

```{r fig.height=10, fig.width=2}
plot_tracks(data_track(dclust, pe))
```

```{r}
d <- dclust$m %>% select(-id_.y) %>% to_matrix(rowcol='gene_id')
s <- colnames(d)
s[pm$colInd]
```


## Gene-body: ordered by correlation


```{r}
dclust <- data_clust('gene_body', opts$n)
r <- dclust$r %>% arrange(r)
s <- r %>% select(id_.x, id_.y)
d <- dclust$em %>% select(id_.x, id_.y, gene_id, sample, met, expr)
d <- s %>% inner_join(d, by=c('id_.x', 'id_.y'))
m <- d %>% select(-expr) %>% spread(sample, met)
e <- d %>% select(-met) %>% spread(sample, expr)
stopifnot(nrow(m) == nrow(s))
stopifnot(nrow(e) == nrow(s))
stopifnot(all(dim(m) == dim(e)))
```

```{r fig.width=10, fig.height=10}
d <- e %>% select(-c(id_.x, id_.y, gene_id)) %>% as.matrix
pe <- plot_heat(d, col=brewer_cols('OrRd'), Rowv=NA)
```

```{r fig.width=10, fig.height=10}
d <- m %>% select(-c(id_.x, id_.y, gene_id)) %>% as.matrix
pm <- plot_heat(d, col=brewer_cols('PuBuGn'), Rowv=NA)
```

```{r fig.height=10, fig.width=2}
d <- r %>% select(r, expr_var, met_var) %>% mutate(i=1:n()) %>%
  gather(param, value, -i)
plot_tracks(d)
```

```{r}
data_clust_var <- function(name_='prom_non_cgi', n=500, genes=F) {
  rs <- dat$rs %>% filter(name == name_) %>% group_by(name, id_.x) %>%
    top_n(1, abs(r)) %>% ungroup
  if (genes) {
    rs <- rs %>% semi_join(select(dat$genes, ens_id), by=c('ens_id'))
  }
  rs <- rs %>% group_by(name) %>% top_n(n, abs(r)) %>% ungroup
  em <- dat$em %>% semi_join(rs, by=c('name', 'id_.x', 'id_.y')) %>%
    select(id_.x, id_.y, gene_id, sample, expr, met)
  e <- em %>% select(id_.y, gene_id, sample, expr) %>% spread(sample, expr)
  m <- em %>% select(id_.y, gene_id, sample, met) %>% spread(sample, met)
  return (list(r=rs, e=e, m=m, em=em))
}


em <- dat$em %>% semi_join(rs, by=c('name', 'id_.x', 'id_.y')) %>%
  select(id_.x, id_.y, gene_id, sample, expr, met)
e <- em %>% select(id_.y, gene_id, sample, expr) %>% spread(sample, expr)
```

