---
title: Gene-specific correlation with cell factors
date: 151023
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(xtable)
options(xtable.type='html')
source('../lib/utils.R')
```

```{r}
opts <- list()
opts$expr <- '../data/expr/data_proc/data_expr.rds'
opts$expr_meta <- '../data/expr/data_proc/data_meta.rds'
opts$met <- '../data/met/join/data_met.rds'
opts$met_meta <- '../data/met/join/data_met.rds'
opts$genes_file <- '../data/expr/data_raw/subpopulation_lif_genes9.csv'
opts$samples_stats <- '../data/samples/samples_stats.csv'
opts$filter_genes <- F
opts$pca_on <- 'gene_body'
opts$alpha <- 0.1
opts$rnd_trials <- 0
opts$min_sites <- 10
opts$cache <- T
opts$mean <- F
opts$permute <- F
opts$num_genes <- 0
opts$annos <- c()
# opts$annos <- c('active_enhancer', 'H3K4me1', 'H3K4me1_Tet1', 'H3K27ac',
#   'H3K27me3', 'cgi', 'prom', 'prom_cgi', 'prom_non_cgi', 'LMR', 'p300',
#   'gene_body', 'Wu_Tet1')
set.seed(0)
```

```{r}
theme_pub <- function() {
  p <- theme(
    axis.text=element_text(size=rel(1.2), color='black'),
    axis.title=element_text(size=rel(1.5)),
    legend.position='top',
    legend.text=element_text(size=rel(1.2)),
    legend.title=element_text(size=rel(1.2)),
    legend.key=element_rect(fill='transparent'),
    panel.border=element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(),
    axis.line = element_line(colour="black", size=1),
    axis.ticks.length = unit(.3, 'cm'),
    axis.ticks.margin = unit(.3, 'cm')
    )
  return (p)
}
```

Significance threshold: `r opts$alpha`

```{r}
cmp <- list()
dat <- list()
```

```{r dat}
read_genes <- function(f) {
  d <- read.csv(f, sep=',', head=T) %>% tbl_df
  names(d) <- c('ens_id', 'gene_id')
  return (d)
}

dat$met <- readRDS(opts$met)
dat$expr <- readRDS(opts$expr)
dat$genes <- read_genes(opts$genes_file)
a <- dat$genes %>% mutate(pluri=T) %>% select(-gene_id)
m <- readRDS(opts$expr_meta)
m <- m %>% left_join(a, by='ens_id')
m[is.na(m$pluri),]$pluri <- F
dat$expr_meta <- m

d <- read.table(opts$samples_stats, sep='\t', head=T) %>%
  select(sample=id, cpg_rate=CpG.rate, chh_rate=CHH.rate, cph_rate=CpH.rate, cov) %>% tbl_df
d <- d[d$sample %in% levels(dat$expr$sample),] %>% droplevels
dat$samples <- d

if (opts$filter_genes) {
  h <- as.vector(dat$genes$ens_id)
  dat$em <- dat$em %>% filter(ens_id %in% h)
}
```

```{r factors}
sample_factors <- function(d) {
  m <- colMeans(d, na.rm=T)
  m <- data.frame(sample=factor(names(m)), factor='context_mean', value=m)

  di <- impute(d)
  pc <- pca(di)
  pcs <- pc$vec
  colnames(pcs) <- sapply(1:ncol(pcs), function(x) sprintf('pc%d', x))
  pcs <- as.data.frame(pcs) %>% mutate(sample=factor(rownames(pcs))) %>%
    gather(factor, value, -sample)

  f <- rbind.data.frame(m, pcs) %>% tbl_df
  return (list(factors=f, pca=pc))
}

d <- dat$met %>% filter(name == opts$pca_on) %>% select(-name, -weight) %>% spread(sample, met)
d <- d %>% select(-c(chromo, start, end, id_)) %>% as.matrix
h <- sample_factors(d)
cmp$pca <- h$pca
f <- h$factors
f <- f %>% filter(factor %in% c('context_mean', 'pc1', 'pc2'))
d <- dat$samples %>% gather(factor, value, -sample)
f <- rbind.data.frame(f, d) %>% droplevels
cmp$f <- f

dat$em <- dat$expr %>% inner_join(f, by='sample') %>%
  mutate(weight=1) %>%
  select(id_, ens_id, sample, name=factor, expr, met=value, weight=weight)
dat$em <- dat$em %>% inner_join(dat$expr_meta, by=c('id_', 'ens_id'))
```

```{r cor, cache=opts$cache}
n <- length(levels(dat$em$sample))
if (opts$permute) {
  permute <- sample(n)
} else {
  permute <- 1:n
}
r <- dat$em %>% group_by(name, id_) %>% do(wtd_cor(.$expr[permute], .$met, .$weight)) %>% ungroup
r <- r %>% group_by(name) %>% mutate(p_fdr=p.adjust(p, method='fdr'), p_adj=p_fdr) %>% ungroup
r <- r %>% inner_join(dat$expr_meta, by=c('id_'))
r <- r %>%
  mutate(name=factor(name)) %>%
  mutate(name=factor(name, levels=rev(sort(levels(name))))) %>%
  arrange(desc(name), p_adj, desc(abs(r)))

saveRDS(r, 'r.rds')
```

```{r}
cmp$r <- r
```

```{r results='asis'}
m <- cmp$f %>% spread(factor, value) %>% select(-sample) %>% as.matrix
xtable(cor(m), digits=2)
```

```{r fig.width=8, fig.height=6}
h <- cmp$pca$vec
rownames(h) <- format_sample(rownames(h))
plot_pca_vec(h)
```




## Statistics


```{r}
cmp$rs <- cmp$r %>% group_by(name) %>% summarise(
  r_mean=mean(r, na.rm=T), n=n(), sig=sum(p_adj <= opts$alpha),
  sig_pos=sum(p_adj <= opts$alpha & r > 0),
  sig_neg=sum(p_adj <= opts$alpha & r < 0)
  ) %>% ungroup %>% arrange(desc(name))
```

```{r results='asis'}
print(xtable(cmp$rs, digits=2))
```


## All sites


```{r fig.height=8}
p <- ggplot(cmp$r, aes(x=name, y=r, fill=name)) +
  geom_hline(yintercept=0, color='darkgrey') +
  geom_boxplot() +
  theme_pub() +
  xlab('') + ylab('\nPearson correlation') + coord_flip() + guides(fill=F)
print(p)
```

```{r fig.width=10, fig.height=12}
d <- cmp$r
d <- d %>% mutate(
  pluri=factor(pluri, levels=c(F, T), labels=c('no', 'yes')),
  name=factor(name, levels=rev(levels(name)))
  )
h <- d %>% group_by(name) %>% top_n(5, 1-p_adj) %>% ungroup %>% select(name, id_) %>% mutate(topn=T)
d <- d %>% left_join(h, by=c('name', 'id_'))
d[is.na(d$topn), 'topn'] <- F
ds <- d %>% group_by(name) %>% summarise(r=mean(r, na.rm=T)) %>% ungroup %>%
  arrange(abs(r)) %>% mutate(name=factor(name, levels=name))
# d <- d %>% mutate(name=factor(name, rev(levels(ds$name))))

p <- ggplot(d, aes(x=r, y=-log10(p_adj), size=-log10(p_adj))) +
  geom_vline(xintercept=0, linetype='dashed', color='darkgrey') +
  geom_vline(data=ds, aes(xintercept=r), color='orange') +
  geom_hline(yintercept=-log10(opts$alpha), color='blue') +
  facet_wrap(~name, ncol=3) +
  scale_color_manual(values=c('no'='black', 'yes'='red3')) +
  geom_point(aes(color=pluri)) +
  geom_point(data=(d %>% filter(pluri=='yes')), color='red') +
  geom_text(data=(d %>% filter(topn == T | (pluri == 'yes' & p_adj <= opts$alpha))), aes(label=gene_id, color=pluri),
    vjust=-0.0, hjust=-0.4) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background=element_rect(fill='transparent'),
    panel.margin = unit(1, "lines")
    ) +
  guides(color=F, size=F) +
  ylim(0, 3.9)
print(p)
```

```{r results='asis'}
h <- d %>% group_by(name) %>% top_n(15, 1 - p_adj) %>% ungroup %>% filter(p_adj <= opts$alpha) %>% select(name, ens_id, gene_id, r, p_adj, pluri) %>% as.data.frame
print(xtable(h, digits=2))
```

```{r fisher_test, eval=F}
fisher_test <- function(a, b) {
  # table: rows == # significant genes, columns == # pluri factors
  h <- fisher.test(as.matrix(table(a, b)))
  return (data.frame(p.value=h$p.value))
}

# Are genes enriched for pluri factors?
d <- cmp$r %>% group_by(id_.x) %>%
  summarise(sig=sum(p_adj <= opts$alpha) > 0, pluri=sum(pluri) > 0)
h <- fisher_test(d$sig, d$pluri)

# Are genes in context enriched for pluri factors?
d <- cmp$r %>% group_by(name, id_.x) %>%
  summarise(sig=sum(p_adj <= opts$alpha) > 0, pluri=sum(pluri) > 0)
h <- d %>% group_by(name) %>% do(fisher_test(.$sig, .$pluri))
```


## Significant sites

```{r fig.height=7}
d <- cmp$r
d <- d %>% group_by(name) %>%
  summarise(
    n=sum(p_adj <= opts$alpha),
    pos=sum(p_adj <= opts$alpha & r > 0),
    neg=sum(p_adj <= opts$alpha & r < 0)) %>%
  ungroup# %>% arrange(n)
h <- d %>% select(-n) %>% gather(sign, n, -name) %>%
    mutate(
      sign=factor(sign, levels=c('pos', 'neg'),
        labels=c('positive', 'negative')),
      name=factor(name, levels=as.vector(d$name))
      )
p <- ggplot(h, aes(x=name, y=n, fill=sign)) +
  geom_bar(stat='identity', position=position_dodge()) +
  scale_fill_manual(values=c('positive'='firebrick2', 'negative'='royalblue')) +
  ylab('\nNumber of significant sites') + coord_flip() +
  guides(fill=guide_legend(title='Correlation')) +
  theme_pub() +
  theme(
    axis.title.y=element_blank()
    )
print(p)
```


```{r fig.height=7}
d <- cmp$r
d <- d %>% group_by(name) %>%
  summarise(
    positive=sum(p_adj <= opts$alpha & r > 0) / n(),
    negative=sum(p_adj <= opts$alpha & r < 0) / n()) %>% gather(sign, n, -name)
ggplot(d, aes(x=name, y=n, fill=sign)) +
  geom_bar(stat='identity', position=position_dodge()) +
  scale_fill_manual(values=c('positive'='firebrick2', 'negative'='royalblue')) +
  xlab('') + ylab('% significant sites') + coord_flip() +
  theme_pub()
```

```{r fig.height=7}
d <- cmp$r
d <- d %>% filter(p_adj <= opts$alpha) %>%
  mutate(ra=abs(r),
    sign=factor(r>0, levels=c(T, F), labels=c('positive', 'negative')),
    name=droplevels(name))
ggplot(d, aes(x=name, y=ra, fill=sign)) + geom_boxplot() +
  scale_fill_manual(values=c('positive'='firebrick2', 'negative'='royalblue')) +
  xlab('') + ylab('Correlation coefficient') + coord_flip() +
  theme_pub()
```



## Visualization

```{r}
select_sites <- function(name_, n_=8) {
  d <- cmp$r %>% filter(name == name_) %>%
    group_by(id_) %>% top_n(1, abs(r)) %>% ungroup %>%
    arrange(desc(abs(r))) %>% head(n_)
  dd <- dat$em %>% semi_join(d, by=c('name', 'id_'))
  return (list(r=d, em=dd))
}

plot_sites <- function(d, ncol_=4) {
  p <- ggplot(d, aes(x=met, y=expr)) +
    stat_smooth(method=lm, color='black', aes(weight=weight)) +
    geom_point(aes(color=sample, size=weight), alpha=0.7) +
    facet_wrap(~gene_id, ncol=ncol_) +
    guides(color=F, size=F)
  print(p)
}

tab_data <- function(d) {
  return (d %>% select(gene_id, ens_id, r, p, p_adj))
}
```

```{r}
opts_chunk$set(fig.width=10, fig.height=6)
```

### Mean

```{r}
d <- select_sites('cpg_rate')
plot_sites(d$em)
```

```{r results='asis'}
print(xtable(tab_data(d$r), digits=2))
```


### PC2

```{r}
d <- select_sites('pc2')
plot_sites(d$em)
```

```{r results='asis'}
print(xtable(tab_data(d$r), digits=2))
```
