---
title: Esrrb
output:
  html_document:
    toc: yes
---

```{r, include=F}
library(knitr)
opts_chunk$set(echo=F, warning=F, message=F, fig.width=10)
```

```{r, include=F}
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)
library(scales)
library(xtable)
source('../lib/utils.R')
source('./viz.R')
```

```{r}
options(xtable.type='html')
```

```{r}
opts <- list()
opts$max_dist <- 10000
opts$win$met_file <- 'w3k_s1k_d20k/data_met.rds'
opts$win$meta_file <- 'w3k_s1k_d20k/data_meta.rds'
opts$em_file <- '../data/join/data.rds'
opts$expr$rate_file <- '../data/expr/data_proc/data_expr.rds'
opts$expr$meta_file <- '../data/expr/data_proc/data_meta.rds'
opts$sample_filter <- c()
opts$init <- T
```

```{r read, eval=opts$init}
filter_samples <- function(d) {
  f <- opts$samples_filter
  if (!is.na(t) & length(f) > 0) {
    d <- d %>% filter(sample %in% f)
  }
  return (d)
}

dat <- list()
dat$win$met <- readRDS(opts$win$met_file) %>% tbl_df %>% filter_samples
dat$win$meta <- readRDS(opts$win$meta_file) %>% tbl_df
dat$expr$rate <- readRDS(opts$expr$rate_file) %>% tbl_df %>% filter_samples
dat$expr$meta <- readRDS(opts$expr$meta_file) %>% tbl_df
dat$em$all <- readRDS(opts$em_file) %>% tbl_df %>% filter_samples
dat$em$meta <- dat$em$all %>% select(-c(sample, expr, met, weight)) %>% distinct
```

```{r eval=opts$init}
cmp <- list()
cmp$r <- readRDS('../gene/r.rds')
```

```{r eval=opts$init}
viz <- list()
viz$sel <- cmp$r %>%
  filter(name %in% c('LMR', 'p300'), gene_id == 'Esrrb', p_adj < 0.1) %>%
  arrange(r) %>% head(2) %>%
  select(ens_id, gene_id, name, id_.x, id_.y, r, p, p_adj, chromo, start.x, end.x, start.y, end.y)
idx <- viz$sel[1,]$id_.x
```

```{r eval=opts$init}
viz$d <- make_data(idx)
```

```{r}
a <- list()
a$gene <- c(86361117, 86521628)
a$TSS <- c(86360117, 86361217)
for (i in 1:nrow(viz$sel)) {
  v <- viz$sel[i,]
  a[[sprintf('%s_%d', v$name, i)]] <- c(v$start.y, v$end.y)
}

viz$da <- data_anno(a)

viz$a <- plot_anno(viz$da)
viz$v <- plot_var(viz$d$v, pa=viz$a, xlab=T)
viz$r <- plot_cor(viz$d$r, pa=viz$a, xlab=T)
viz$m <- plot_met(viz$d$em, pa=viz$a)
```

```{r tracks, fig.width=14, fig.height=10}
grid.arrange(viz$v, viz$r, viz$m, nrow=3, heights=c(0.25, 0.25, 0.5))
```

```{r eval=F}
write.csv(viz$v$data, 'fig2b_var.csv')
write.csv(viz$r$data, 'fig2b_cor.csv')
write.csv(viz$m$data, 'fig2b_cpg.csv')
```

```{r results='asis'}
xtable(viz$sel, digits=4)
```

```{r scatter, fig.width=6, fig.height=6}
ps <- list()
for (i in 1:nrow(viz$sel)) {
  v <- viz$sel[i,]
  p <- plot_scatter(as.character(v$name), v$id_.x, v$id_.y)
  ps[[length(ps) + 1]] <- p
  print(p)
}
```

```{r eval=F}
write.csv(ps[[1]]$data, 'fig2b_p300.csv')
write.csv(ps[[2]]$data, 'fig2b_LMR.csv')
```


```{r}
opts_chunk$set(eval=F)
```

```{r}
pdf(file='fig_esrrb.pdf', width=18, height=10)
grid.arrange(viz$v, viz$r, viz$m, nrow=3, heights=c(0.25, 0.25, 0.5))
dev.off()
```

```{r eval=F}
ggsave(viz$m, file='met_annos.jpg', width=18, height=6, dpi=600)

h <- list()
h$v <- plot_var(viz$d$v, xlab=T)
h$r <- plot_cor(viz$d$r, xlab=T)
h$m <- plot_met(viz$d$em)
h$m
ggsave(h$m, file='met.jpg', width=18, height=6, dpi=600)
# grid.arrange(h$v, h$r, h$m, nrow=3, heights=c(0.25, 0.25, 0.5))
```



```{r}
s <- viz$sel %>% select(ens_id, gene_id, name, chromo, start=start.y, end=end.y, r, p_value=p_adj)
write.table(s, file='fig_esrrb.csv', sep='\t')
```

```{r}
for (i in 1:nrow(viz$sel)) {
  v <- viz$sel[i,]
  p <- plot_scatter(v$name, v$id_.x, v$id_.y)
  ggsave(p, file=sprintf('fig_esrrb_%d.pdf', i), width=6.5, height=6)
}
```
